import type { App, Plugin } from 'vue';
import {
  AccordionPlugin,
  AffixPlugin,
  AvatarPlugin,
  AvatarGroupPlugin,
  BadgePlugin,
  BreadcrumbsPlugin,
  ButtonPlugin,
  CollapsePlugin,
  ConfigProviderPlugin,
  ModalPlugin,
  InplacePlugin,
  DrawerPlugin,
  DropdownPlugin,
  ImagePlugin,
  PaginationPlugin,
  PlaceholderPlugin,
  ScrollbarPlugin,
  SpinnerPlugin,
  TabsPlugin,
  TagPlugin,
  TextPlugin,
  ContainerPlugin,
  ColPlugin,
  RowPlugin,
  FormPlugin,
  FormItemPlugin,
  InputPlugin,
  CheckboxPlugin,
  CheckboxButtonPlugin,
  CheckboxGroupPlugin,
  DatepickerPlugin,
  InputRangePlugin,
  InputPasswordPlugin,
  InputNumberPlugin,
  InputMaskPlugin,
  InputFilePlugin,
  InputCodePlugin,
  RadioPlugin,
  RadioButtonPlugin,
  RadioGroupPlugin,
  SwitchPlugin,
  SelectPlugin,
  OverlayPlugin,
  AlertPlugin,
  ToastPlugin,
  ConfirmPlugin,
  ProgressPlugin,
  DividerPlugin,
  FlexPlugin,
  TablePlugin,
  InputGroupPlugin
} from '../components';
import {
  VisiblePlugin,
  ClickOutsidePlugin,
  LoadingPlugin,
  TooltipPlugin
} from '../directives';

export const VauUI: Plugin = {
  install (app: App) {
    // Components
    app.use(AccordionPlugin);
    app.use(AffixPlugin);
    app.use(AvatarPlugin);
    app.use(AvatarGroupPlugin);
    app.use(BadgePlugin);
    app.use(BreadcrumbsPlugin);
    app.use(ButtonPlugin);
    app.use(CollapsePlugin);
    app.use(ConfigProviderPlugin);
    app.use(ModalPlugin);
    app.use(InplacePlugin);
    app.use(DrawerPlugin);
    app.use(DropdownPlugin);
    app.use(ImagePlugin);
    app.use(PaginationPlugin);
    app.use(PlaceholderPlugin);
    app.use(ScrollbarPlugin);
    app.use(SpinnerPlugin);
    app.use(TabsPlugin);
    app.use(TagPlugin);
    app.use(TextPlugin);
    app.use(ContainerPlugin);
    app.use(ColPlugin);
    app.use(RowPlugin);
    app.use(FormPlugin);
    app.use(FormItemPlugin);
    app.use(InputPlugin);
    app.use(CheckboxPlugin);
    app.use(CheckboxButtonPlugin);
    app.use(CheckboxGroupPlugin);
    app.use(DatepickerPlugin);
    app.use(InputRangePlugin);
    app.use(InputPasswordPlugin);
    app.use(InputNumberPlugin);
    app.use(InputMaskPlugin);
    app.use(InputFilePlugin);
    app.use(InputCodePlugin);
    app.use(RadioPlugin);
    app.use(RadioButtonPlugin);
    app.use(RadioGroupPlugin);
    app.use(SwitchPlugin);
    app.use(SelectPlugin);
    app.use(SelectPlugin);
    app.use(OverlayPlugin);
    app.use(AlertPlugin);
    app.use(ToastPlugin);
    app.use(ConfirmPlugin);
    app.use(ProgressPlugin);
    app.use(DividerPlugin);
    app.use(FlexPlugin);
    app.use(TablePlugin);
    app.use(InputGroupPlugin);

    // Directives
    app.use(VisiblePlugin);
    app.use(ClickOutsidePlugin);
    app.use(LoadingPlugin);
    app.use(TooltipPlugin);
  }
};
